### ISSUE TITLE
Gnome-keyring and Seahorse 3.34.0 upgrade in Archlinux broke logout / shutdown process.

### ISSUE THREAD

**Issue by FredBezies** [mate-desktop/mate-session-manager#222] opened 2019-10-02 20:44 UTC
#### Expected behaviour

Mate-Desktop logout or shutdown without any problem.

#### Actual behaviour

A dialog box is appearing telling me that at-spi-bus-launcher is not answering, asking me to wait or kill the process to proceed anyway.

#### Steps to reproduce the behaviour

1. Install archlinux with Mate-Desktop
2. Be sure to have gnome-keyring and seahorse 3.34.0

#### MATE general version

1.22.2

#### Package version

Gnome-keyring 3.34.0
Mate-session-manager 1.22.1

#### Linux Distribution

Archlinux

#### Link to downstream report of your Distribution

Bug reported here: https://bugs.archlinux.org/task/63995

**Comment by FredBezies** [comment] 2019-10-03 08:28
More info. Opened a bug on gnome-keyring bug tracker: https://gitlab.gnome.org/GNOME/gnome-keyring/issues/40

**Comment by jmakovicka** [comment] 2019-10-03 19:42
According to GNOME's response, keyring needs to be spawned asynchronously, and its output and exit code needs to be handled in the main loop so the DBUS request from gnome-keyring-daemon can be processed.

**Comment by philmmanjaro** [comment] 2019-10-04 07:22
That is now the latest comment:

> The entire point of the patch is that the calls are handled before the application quits (well, before gnome-session registers that the application is quit, but same thing). So if mate session manager waits for the process to quit before handling the dbus calls, then we are in an unsolvable situation.

**Comment by jmakovicka** [comment] 2019-10-04 19:13
Actually, the fix in MATE is easier than I thought. The problematic code in MSM is basically do-nothing now, because GNOME_KEYRING_PID exposure was removed from gnome-keyring in 2014, and it can be just removed.

I hope to post a PR soon.

**Comment by jmakovicka** [comment] 2019-10-04 19:20
Created a PR: https://github.com/mate-desktop/mate-session-manager/pull/223

**Comment by raveit65** [comment] 2019-10-06 10:58
I can confirm the problem with fedora-31-beta.

**Comment by flexiondotorg** [comment] 2019-10-06 13:00
I was going to review this patch but Ubuntu 19.10 is currently shipping a patched gnome-keyring 3.31 and therefore unaffected.

**Comment by jmakovicka** [comment] 2019-10-06 13:45
This change should be fine with gnome-keyring >= 3.11.92

**Comment by FredBezies** [comment] 2019-10-06 14:07
Just for information: Archlinux added this patch for mate-session-manager 1.22.2-1 (https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/mate-session-manager&id=4f82f6addb79099948cb8167c9aaf70e9c0aa2f8) and Manjaro does the same. So this patch is working :)

**Comment by jmakovicka** [comment] 2019-10-06 14:41
Please update the Arch patch to the most recent version of #223, this one does not report an error properly if gnome-keyring-daemon crashes on startup.

**Comment by raveit65** [comment] 2019-10-06 15:08
> This change should be fine with gnome-keyring >= 3.11.92

Sounds good. gnome-3.12 is very old, so it seems to be save to merge it to 1.22 branch.
It fixes the issue in f31 beta and i can test it with fedora 30 (gnome-keyring-3.31) 
@sc0w @monsta 
Is this OK for debian?

**Comment by sc0w** [comment] 2019-10-06 19:15
I confirm the issue in debian testing (with gnome-keyring 3.34.0-1)

Debian stable (with mate 1.20) isn't affected

@raveit65 yes (I didn't test the PR yet)

**Comment by philmmanjaro** [comment] 2019-10-07 07:19
> Please update the Arch patch to the most recent version of #223, this one does not report an error properly if gnome-keyring-daemon crashes on startup.

At Manjaro we updated now to the latest patch.

**Comment by monsta** [comment] 2019-10-08 11:20
> A dialog box is appearing telling me that at-spi-bus-launcher is not answering, asking me to wait or kill the process to proceed anyway.

Interesting, I saw this in Debian Testing some time before Buster release, but eventually it disappeared (still before Buster release). I thought it was some problem with AT-SPI.

Well, now I have fully updated Debian Testing VM, but can't reproduce the issue. I'll check the patch anyway.

**Comment by sc0w** [comment] 2019-10-08 13:10
Fixed with https://github.com/mate-desktop/mate-session-manager/pull/223

**Closed by sc0w** 2019-10-08 13:10 UTC
Labels: confirmed
