### ISSUE TITLE
"i3" entry in session properties silently vanishes

### ISSUE THREAD

**Issue by eater** [mate-desktop/mate-session-manager#191] opened 2019-03-05 16:59 UTC
#### Expected behaviour
When I manually create a new entry in mate-session-properties, I expect that the entry will be created. 

#### Actual behaviour
When I manually create a new entry in mate-session-properties, if the content of the entry is "/usr/bin/i3", the next time I open mate-session-properties, the entry is gone, with no explanation.

#### Steps to reproduce the behaviour
1. Launch mate-session-properties.
2. Click the Add button to open the dialog.
3. Add a startup program: 
        Name: i3 window manager
        Command: /usr/bin/i3
        Comment: eye three!
4. Click the Add button to confirm the dialog.
5. Observe that "i3 window manager" now appears in the list of startup programs.
6. Close the mate-session-properties window.
7. Launch mate-session-properties again.
8. Observe that the newly added i3 entry has disappeared.
9. This doesn't happen if I add other entries. 

#### MATE general version
1.20.1

#### Package version
1.20.0

#### Linux Distribution
Xubuntu 18.04

**Comment by raveit65** [comment] 2019-03-05 19:35
I can't reproduce that. I created a dummy entry for testing with mate-session-properties.
After closing the application i see that enty in autostart folder.
```
[rave@mother ~]$ ls -l .config/autostart/
insgesamt 76
<cut>
-rw-rw-r-- 1 rave rave   229  5. Mär 20:30 i3.desktop
<cut>
[rave@mother ~]$ cat .config/autostart/i3.desktop 
[Desktop Entry]
Type=Application
Exec=i3
Hidden=false
X-MATE-Autostart-enabled=true
Name[de_DE]=i3-WindowManger
Name=i3-WindowManger
Comment[de_DE]=starts i3 Window-manger
Comment=starts i3 Window-manger
X-MATE-Autostart-Delay=0
[rave@mother ~]$ 
```

**Comment by raveit65** [comment] 2019-03-05 20:47
Of course the entry is there after session restart in fedora.

**Comment by eater** [comment] 2019-03-06 00:05
Thanks for trying to replicate. Interestingly, checking now, I have a ~/.config/autostart/i3.desktop file too, creation date this morning:
`
[Desktop Entry]
Type=Application
Name=i3
Comment=i3
Exec=i3
Hidden=false
X-MATE-Autostart-enabled=true
Name[en_US]=i3 wm
Comment[en_US]=eye three!
`
However, it doesn't appear in the GUI application list.

**Comment by raveit65** [comment] 2019-03-06 07:54
The entry displays in GUI after system restart this morning.
![bildschirmfoto zu 2019-03-06 08-51-34](https://user-images.githubusercontent.com/961604/53864632-4b061680-3fed-11e9-97bd-b169bbbb5397.png)

**Comment by raveit65** [comment] 2021-04-22 16:40
Fixed for master and stable branch.
https://github.com/mate-desktop/mate-session-manager/pull/279
https://github.com/mate-desktop/mate-session-manager/pull/274

**Closed by raveit65** 2021-04-22 16:40 UTC
Labels: unconfirmed
